MAINFILE = slides
LATEX = pdflatex
SUBFILES = *.tex
REFFILE = ref.bib



all: $(SUBFILES)
	$(LATEX) $(MAINFILE).tex

clean:
	rm -f slides.aux slides.dvi slides.log slides.pdf slides.bbl slides.fdb_latexmk slides.nav slides.snm slides.toc slides.blg slides.fls slides.out slides.synctex.gz
